# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myDate', models.CharField(max_length=200, verbose_name='\u0627\u0644\u0639\u0635\u0631')),
            ],
            options={
                'verbose_name_plural': '\u0627\u0644\u0639\u0635\u0631',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0642\u0635\u064a\u062f\u0629')),
                ('myDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.MyDate', verbose_name='\u0627\u0644\u0639\u0635\u0631')),
            ],
            options={
                'verbose_name_plural': '\u0627\u0644\u0642\u0635\u064a\u062f\u0629',
            },
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200, verbose_name='\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0635\u0648\u0631\u0629')),
                ('name', models.CharField(max_length=200, verbose_name='\u0627\u0644\u0634\u0627\u0639\u0631')),
            ],
            options={
                'verbose_name_plural': '\u0627\u0644\u0634\u0627\u0639\u0631',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u062f\u0627\u0631 \u0627\u0644\u0646\u0634\u0631')),
            ],
            options={
                'verbose_name_plural': '\u062f\u0627\u0631 \u0627\u0644\u0646\u0634\u0631',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, verbose_name='\u0627\u0644\u063a\u0631\u0636')),
            ],
            options={
                'verbose_name_plural': '\u0627\u0644\u063a\u0631\u0636',
            },
        ),
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea', models.CharField(max_length=200, verbose_name='\u0627\u0644\u0628\u062d\u0631')),
            ],
            options={
                'verbose_name_plural': '\u0628\u062d\u0631 \u0627\u0644\u0642\u0635\u064a\u062f\u0629',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='\u0627\u0644\u0628\u064a\u062a')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.Poem')),
            ],
            options={
                'verbose_name_plural': '\u0628\u064a\u062a \u0627\u0644\u0642\u0635\u064a\u062f\u0629',
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.Poet', verbose_name='\u0627\u0644\u0634\u0627\u0639\u0631'),
        ),
        migrations.AddField(
            model_name='poem',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.Publisher', verbose_name='\u062f\u0627\u0631 \u0627\u0644\u0646\u0634\u0631'),
        ),
        migrations.AddField(
            model_name='poem',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.Purpose', verbose_name='\u0627\u0644\u063a\u0631\u0636'),
        ),
        migrations.AddField(
            model_name='poem',
            name='sea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.Sea', verbose_name='\u0627\u0644\u0628\u062d\u0631'),
        ),
    ]
